from sqlalchemy.orm import Session

from . import models, schemas
from fastapi.exceptions import HTTPException

def get_user(db: Session, user_id: int):
    return db.query(models.User).filter(models.User.id == user_id).first()


def get_user_by_email(db: Session, email: str):
    return db.query(models.User).filter(models.User.email == email).first()


def get_users(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.User).offset(skip).limit(limit).all()


def create_user(db: Session, user: schemas.UserCreate):
    fake_hashed_password = user.password + "notreallyhashed"
    db_user = models.User(email=user.email, hashed_password=fake_hashed_password)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user


def get_items(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.Item).offset(skip).limit(limit).all()


def create_user_item(db: Session, item: schemas.ItemCreate, user_id: int):
    db_item = models.Item(**item.model_dump(), owner_id=user_id)
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item

def delete_user(db:Session , user_id: int):
    db_User = db.query(models.User).filter(models.User.id == user_id).first()
    if db_User is None:
        raise HTTPException(status_code=404, detail="User not found")
    db.delete(db_User)
    db.commit()
    db.close()
    return {"message": "User deleted successfully"}
    
def update_user(db:Session , user_id: int ,user: schemas.User):
    db_user = db.query(models.User).filter(models.User.id == user_id).first()
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    db.update(user)
    db.commit()
    db.close()
    return {"updated user ": user}